language: r
warnings_are_errors: false

script:
  - Rscript -e "source('data-raw/process_tides.R')"
  - Rscript -e "source('data-raw/process_meteorology.R')"
 
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  keep_history: true
  target_branch: master        # Add this line - To push into GitHub master branch
  on:
    branch: staging
addons:
  apt:
    packages:
      - libgit2-dev
